export const decListItems = [{
  key: 'gNo',
  label: '项号'
}, {
  key: 'gNoAll',
  label: '项号及备案序号'
}, {
  key: 'contrItem',
  label: '备案序号'
}, {
  key: 'codeTs',
  label: '商品编号'
}, {
  key: 'priceAndTotal',
  label: '单价/总价/币制'
}, {
  key: 'ciqName',
  label: '检验检疫名称'
}, {
  key: 'goodsSpec',
  label: '检验检疫货物规格'
}, {
  key: 'gName',
  label: '商品名称'
}, {
  key: 'gModel',
  label: '规格型号'
}, {
  key: 'gQty',
  label: '成交数量'
}, {
  key: 'gUnit',
  label: '成交计量单位'
}, {
  key: 'declPrice',
  label: '单价'
}, {
  key: 'declTotal',
  label: '总价'
}, {
  key: 'tradeCurr',
  label: '币制'
}, {
  key: 'qty1',
  label: '法定第一数量'
}, {
  key: 'unit1',
  label: '法定第一计量单位'
}, {
  key: 'exgVersion',
  label: '加工成品单耗版本号'
}, {
  key: 'exgNo',
  label: '货号'
}, {
  key: 'destinationCountry',
  label: '最终目的国（地区）'
}, {
  key: 'qty2',
  label: '法定第二数量'
}, {
  key: 'unit2',
  label: '法定第二计量单位'
}, {
  key: 'originCountry',
  label: '原产国（地区）'
}, {
  key: 'districtCode',
  label: '境内目的地'
}, {
  key: 'destCode',
  label: ''
}, {
  key: 'dutyMode',
  label: '征免方式'
}, {
  key: 'ciqCode',
  label: '检验检疫编码及名称'
}, {
  key: 'goodsSpec',
  label: '检验检疫货物规格'
}, {
  key: 'showGoodsAttrValue',
  label: '货物属性'
}, {
  key: 'purpose',
  label: '用途'
}, {
  key: 'licenseTypeNo',
  label: '许可证类别及编号'
}, {
  key: 'dangerGoodsInfo',
  label: '危险货物信息'
}, {
  key: 'gNameAndModel',
  label: '商品名称、规格型号'
}, {
  key: 'gQtyAndUnit',
  label: '数量及单位'
}]
