export const decHeadItems = [{
  key: 'customMaster',
  label: '申报地海关'
}, {
  key: 'iEPort',
  label: '进/出境关别'
}, {
  key: 'manualNo',
  label: '备案号'
}, {
  key: 'contrNo',
  label: '合同协议号'
}, {
  key: 'iEDate',
  label: '进口日期'
}, {
  key: 'tradeCodeScc',
  label: '境内收发货人统一社会信用代码'
}, {
  key: 'tradeCusCode',
  label: '境内收发货人海关编码'
}, {
  key: 'tradeCiqCode',
  label: '境内收发货人检验检疫编码'
}, {
  key: 'tradeName',
  label: '境内收发货人名称'
}, {
  key: 'overseasConsignorCode',
  label: '境外收发货人代码'
}, {
  key: 'overseasConsignorEname',
  label: '境外收发货人名称'
}, {
  key: 'ownerCodeScc',
  label: '消费使用单位统一社会信用代码'
}, {
  key: 'ownerCusCode',
  label: '消费使用单位海关编码'
}, {
  key: 'ownerCiqCode',
  label: '消费使用单位检验检疫编码'
}, {
  key: 'ownerName',
  label: '消费使用单位名称'
}, {
  key: 'agentCodeScc',
  label: '申报单位统一社会信用代码'
}, {
  key: 'agentCusCode',
  label: '申报单位海关编码'
}, {
  key: 'agentCiqCode',
  label: '申报单位检验检疫编码'
}, {
  key: 'agentName',
  label: '申报单位名称'
}, {
  key: 'trafMode',
  label: '运输方式'
}, {
  key: 'trafName',
  label: '运输工具名称'
}, {
  key: 'voyageNo',
  label: '航次号'
}, {
  key: 'billNo',
  label: '提运单号'
}, {
  key: 'tradeMode',
  label: '监管方式'
}, {
  key: 'cutMode',
  label: '征免性质'
}, {
  key: 'licenseNo',
  label: '许可证号'
}, {
  key: 'tradeCountry',
  label: '启运国/运抵国（地区）'
}, {
  key: 'distinatePort',
  label: '经停港/指运港'
}, {
  key: 'transMode',
  label: '成交方式'
}, {
  key: 'feeMark',
  label: '运费标识'
}, {
  key: 'feeRate',
  label: '运费数值'
}, {
  key: 'feeCurr',
  label: '运费币制代码'
}, {
  key: 'insurMark',
  label: '保费标识'
}, {
  key: 'insurRate',
  label: '保费数值'
}, {
  key: 'insurCurr',
  label: '保费币制代码'
}, {
  key: 'otherMark',
  label: '杂费标识'
}, {
  key: 'otherRate',
  label: '杂费数值'
}, {
  key: 'otherCurr',
  label: '杂费币制代码'
}, {
  key: 'packNo',
  label: '件数'
}, {
  key: 'wrapType',
  label: '包装种类'
}, {
  key: 'grossWt',
  label: '毛重'
}, {
  key: 'netWt',
  label: '净重'
}, {
  key: 'tradeArea',
  label: '贸易国别（地区）'
}, {
  key: 'goodSplace',
  label: '货物存放地点'
}, {
  key: 'despPort',
  label: '启运港'
}, {
  key: 'despDate',
  label: '启运日期'
}, {
  key: 'entyPort',
  label: '入/离境口岸'
}, {
  key: 'entryType',
  label: '报关单类型'
}, {
  key: 'markNo',
  label: '标记唛码'
}, {
  key: 'noteS',
  label: '备注'
}, {
  key: 'billType',
  label: '清单类型'
}]
